minimumReleaseAge: 4320

onlyBuiltDependencies:
  - aws-crt
  - esbuild

overrides:
  "ws@7.5.9": 7.5.10
  "ws@8.14.2": 8.17.1
  "qs@6.11.0": 6.14.1
  "qs@6.13.0": 6.14.1
  "form-data@4.0.0": 4.0.4
  "body-parser@1.20.1": 1.20.3
  "braces@3.0.2": 3.0.3
  "path-to-regexp@0.1.7": 0.1.12
  "axios@1.6.1": 1.12.0
  "@remix-run/router@1.23.0": 1.23.2
