name: Tarjonta-pulssi
env:
  HUSKY: 0

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
        name: Install pnpm
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - name: Run tests
        run: |
          pnpm install
          pnpm run typecheck
          pnpm run prettier
          pnpm run eslint
          pnpm run test
